"""The Hypothesis-weighted candidate scorer -- resolution ladder rung 5.

A pure function of two spans of text: no store, no vault handle, no config,
no I/O. Given a candidate window generated by
:mod:`knotica.core.notes.candidates` and the anchor's own already-extracted
historical quote/prefix/suffix (rung 0's job, not this module's),
:func:`score_candidate` combines four ``difflib.SequenceMatcher.ratio()``
terms and a position term into one weighted sum; :func:`score_candidates`
argmaxes that score over a whole candidate set.

**Calibration caveat.** The weights (quote 50, prefix 20, suffix 20, position
2; normaliser 92) are Hypothesis's published formula, cited as-is -- they
have never been validated against this project's own corpus. The
fuzzy/orphan rate this formula produces on real notes is unknown until Phase
2 runs against real data; that measurement is itself a Phase 2 deliverable
feeding a later architectural decision. Treat the weights as a borrowed
prior, not a tuned parameter -- do not adjust them here.

Position is normalised by the *page* (``head_text``), not the quote: ``1 -
offset_delta / len(head_text)``. Normalising by quote length goes wildly
negative for any real relocation (a 50-character quote moving 2000
characters gives ``1 - 40 = -39``) and, even at the position term's small
2/92 weight, can invert the argmax; normalising by the page keeps the term
bounded for any two offsets inside the same document. The term is clamped
to ``>= 0.0`` defensively.

**Sub-span alignment -- the candidate is trimmed before it is scored.** A
candidate window is only ever an *approximation* of where the quote now
lives: rung 4 proposes sentence-bounded spans, so a quote that was captured
as a clause inside a sentence gets a window roughly twice its own length.
``SequenceMatcher.ratio()`` is ``2*M / (len(a) + len(b))``, so scoring the
quote against that whole width caps the ratio near
``2*q / (q + 2*q) = 0.667`` **even when every character of the quote is
present in the window verbatim** -- at which point a one-character typo and a
heavy paraphrase become indistinguishable and the score stops tracking edit
distance at all. :func:`align_candidate` therefore locates the sub-span of
the window the quote actually aligns to, and :func:`score_candidate` scores
*that*: its quote ratio, the prefix and suffix drawn from around it, and its
own start for the position term. :func:`score_candidates` reports the aligned
span alongside the winning score, so a caller rendering the result to a human
shows the span whose score it is displaying.

The aligned sub-span is the window's **matched extent**: from the start of
the first block the quote matches to the end of the last. That is not a
second scoring pass -- the blocks are a correspondence the matcher already
had to compute -- and it cannot manufacture agreement that is not there.
``ratio()``'s denominator still carries ``len(quote)``, so a sub-span
narrower than the quote is *penalised*, not flattered; and a window whose
matches are scattered across its whole width yields an extent equal to that
width, i.e. alignment degrades to a no-op exactly where there is no coherent
region to align to. Taking a fixed ``len(quote)`` slice instead was measured
against this and rejected: it discards matching material outside the slice,
which costs paraphrase recall for no gain in precision.

The matcher used for alignment disables ``difflib``'s ``autojunk`` heuristic,
which discards any element occurring in more than 1% of a sequence of length
200 or more; at *character* granularity that junks ordinary letters out of
any window past a couple of sentences, leaving the extent anchored on noise.

A candidate's own quote/prefix/suffix are extracted from ``head_text`` with
the same :data:`CONTEXT_WINDOW`-character window rung 0 uses to extract the
anchor's historical context, so the comparison is like-for-like rather than
reporting a length mismatch as a content difference. ``resolve.py``'s rung-0
extraction imports this constant rather than restating the literal.

Symmetry is enforced here, not assumed of the caller: the incoming
historical ``prefix``/``suffix`` are themselves truncated to
:data:`CONTEXT_WINDOW` before either ratio is computed -- the prefix to its
*tail* (the characters nearest the quote) and the suffix to its *head* (the
characters nearest the quote), matching the direction each was extracted
in. Without this, ``SequenceMatcher.ratio() = 2*M / (len(a) + len(b))`` is
capped by whichever side is longer than the window, so a verbatim,
word-for-word match can lose several hundredths of a point to nothing but a
length mismatch -- exactly the margin that separates ``fuzzy`` from
``orphaned`` at ``guess_threshold``. Truncating both sides to the same width
makes the ratio measure content similarity, not string-length disparity.

Short or truncated context gets no special-casing: prefix and suffix are
opaque strings, and near a page boundary the extracted window is simply
shorter than :data:`CONTEXT_WINDOW`. ``SequenceMatcher.ratio()`` already
handles this correctly on its own -- empty-vs-empty scores ``1.0`` (neither
side has context, so they agree) and empty-vs-non-empty scores ``0.0`` --
so no branch is added for it here.
"""

from __future__ import annotations

from difflib import SequenceMatcher

__all__ = [
    "CONTEXT_WINDOW",
    "NORMALISER",
    "POSITION_WEIGHT",
    "PREFIX_WEIGHT",
    "QUOTE_WEIGHT",
    "SUFFIX_WEIGHT",
    "align_candidate",
    "score_candidate",
    "score_candidates",
]

# Hypothesis's published weights and normaliser -- see the calibration
# caveat in the module docstring.
QUOTE_WEIGHT = 50
PREFIX_WEIGHT = 20
SUFFIX_WEIGHT = 20
POSITION_WEIGHT = 2
NORMALISER = 92

# The width resolution rung 0 extracts the anchor's historical prefix/suffix
# with. Declared once here so a candidate's own prefix/suffix -- extracted
# below -- is comparable to the anchor's like-for-like, never a second
# literal.
CONTEXT_WINDOW = 32


def align_candidate(quote: str, head_text: str, candidate: tuple[int, int]) -> tuple[int, int]:
    """The sub-span of ``candidate`` that ``quote`` actually aligns to.

    The window's matched extent: from the start of the first block ``quote``
    matches to the end of the last. Returns ``candidate`` unchanged when the
    window is already no wider than ``quote`` (there is nothing to trim) or
    when the two share no character at all (there is nothing to align to). See
    the module docstring for why the whole width would otherwise cap the quote
    ratio, and for why the extent cannot inflate a score.
    """
    start, end = candidate
    if end - start <= len(quote):
        return candidate

    window = head_text[start:end]
    matcher = SequenceMatcher(None, quote, window, autojunk=False)
    matched = [block for block in matcher.get_matching_blocks() if block.size]
    if not matched:
        return candidate

    first = min(block.b for block in matched)
    last = max(block.b + block.size for block in matched)
    return start + first, start + last


def score_candidate(
    candidate: tuple[int, int],
    head_text: str,
    quote: str,
    prefix: str,
    suffix: str,
    historical_offset: int,
) -> float:
    """Score one ``candidate`` span against the anchor's recorded context.

    ``quote``/``prefix``/``suffix`` are the anchor's own historical strings,
    already extracted by the caller (resolution rung 0). This function aligns
    ``candidate`` to its best-matching sub-span (:func:`align_candidate`),
    derives the *candidate's own* quote/prefix/suffix from ``head_text`` there,
    and combines the three similarity ratios with a position term via the
    weighted formula documented on the module.
    """
    start, end = align_candidate(quote, head_text, candidate)
    candidate_quote = head_text[start:end]
    candidate_prefix = head_text[max(0, start - CONTEXT_WINDOW) : start]
    candidate_suffix = head_text[end : end + CONTEXT_WINDOW]

    # Bound the historical side to the same window before comparing, so a
    # longer recorded prefix/suffix cannot cap the ratio on length alone --
    # see the module docstring.
    windowed_prefix = prefix[-CONTEXT_WINDOW:]
    windowed_suffix = suffix[:CONTEXT_WINDOW]

    quote_ratio = _ratio(quote, candidate_quote)
    prefix_ratio = _ratio(windowed_prefix, candidate_prefix)
    suffix_ratio = _ratio(windowed_suffix, candidate_suffix)
    position_term = _position_term(start, historical_offset, head_text)

    weighted_sum = (
        QUOTE_WEIGHT * quote_ratio
        + PREFIX_WEIGHT * prefix_ratio
        + SUFFIX_WEIGHT * suffix_ratio
        + POSITION_WEIGHT * position_term
    )
    return weighted_sum / NORMALISER


def score_candidates(
    candidates: tuple[tuple[int, int], ...],
    head_text: str,
    quote: str,
    prefix: str,
    suffix: str,
    historical_offset: int,
) -> tuple[tuple[int, int], float] | None:
    """The argmax of :func:`score_candidate` over ``candidates``.

    The score is that argmax; the span reported alongside it is the *aligned*
    sub-span of the winning window -- the span the score was actually computed
    for, not the wider window it was located inside. A caller that renders the
    result to a human therefore shows the placement its number describes.

    Returns ``None`` for an empty candidate set rather than raising -- an
    empty candidate set is a normal, expected rung-4 outcome (a quote whose
    seed words do not occur in the page at all), not a programming error,
    and rung 9 ("orphaned, no guess") is exactly the branch that consumes
    it.
    """
    if not candidates:
        return None

    best_window = candidates[0]
    best_score = score_candidate(best_window, head_text, quote, prefix, suffix, historical_offset)
    for candidate in candidates[1:]:
        candidate_score = score_candidate(
            candidate, head_text, quote, prefix, suffix, historical_offset
        )
        if candidate_score > best_score:
            best_window, best_score = candidate, candidate_score
    return align_candidate(quote, head_text, best_window), best_score


def _position_term(start: int, historical_offset: int, head_text: str) -> float:
    """``1 - offset_delta / len(head_text)``, clamped to ``>= 0.0``."""
    if not head_text:
        return 1.0
    offset_delta = abs(start - historical_offset)
    return max(1 - offset_delta / len(head_text), 0.0)


def _ratio(a: str, b: str) -> float:
    """The similarity primitive shared by all three ratio terms."""
    return SequenceMatcher(None, a, b).ratio()
